include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/firebase_options.dart"

linter:
  rules:
    prefer_const_constructors: true
    directives_ordering: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    sort_constructors_first: true
    prefer_constructors_over_static_methods: true
    avoid_types_on_closure_parameters: true
    omit_local_variable_types: true
    prefer_function_declarations_over_variables: true
    unawaited_futures: true
    use_super_parameters: true
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
