name: simple_ai_dnd_chat_app
description: "A Flutter chat app with an AI Dungeon Master for D&D-style roleplay adventures."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  firebase_ai: ^3.1.0
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  hive_ce_flutter: ^2.3.1
  intl: ^0.20.2
  markdown: ^7.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.2

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Bold.ttf
          weight: 700
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/ibm_plex_mono/IBMPlexMono-Regular.ttf
          weight: 400
    - family: Vidaloka
      fonts:
        - asset: assets/fonts/vidaloka/Vidaloka-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#1C1917"
  image: "assets/icon/main_icon.png"

icons_launcher:
  platforms:
    web:
      enable: true
      image_path: "assets/icon/main_icon.png"
